<article>

# Policy management # {#h-manage}

Based on the [=resource descriptions=] provided by the [=[RS]=], the [=[AS]=] enables the [=[RO]=] to manage policies that govern the authorization on interaction with those [=resources=]. The specific user interface(s) through which the [=[RO]=] can exert this control is out of the scope of this specification. This section only specifies the conformance with respect to the **affordances** such an interface [MUST] provide to the [=[RO]=].

For each [=asset=] in the [=[AS]'s=] knowledge base, the [=[AS]=] [MUST] provide the [=[RO]=] with the following affordances.

  - For each [=scope=] linked to the [=asset=], the [=[AS]=] [MUST] allow the [=[RO]=] to define the policy under which interactions with the [=resource=] within that [=scope=] are authorized.

  - For each [=scope=] linked to an [=asset collection=] of which the [=asset=] is the [=source=], the [=[AS]=] [MUST] allow the [=[RO]=] to define the default policy under which interactions within that [=scope=] are authorized on [=resources=] that are part of the [=collection=], in case these [=resources=] do not have a policy for that [=scope=] themselves.

  ISSUE: clarify what 'policies'/'criteria' are, and whether each AS is obliged to support them all, or urged to provide a certain minimum set ....

In providing these affordances to the [=[RO]=], the [=[AS]=] [SHOULD] take into account each [=asset's=] metadata: the [=resource's type=], [=resource's name|name=], [=resource's description|description=] and [=resource's icon|icon=] from the [=resource description=], and the [=scope's name=], [=scope's description|description=] and [=scope's icon|icon=] from the [=scope description=]. These metadata [SHOULD] be used to maximize the potential for the [=[RO]=] to make an **informed policy decision**.

</article>
