<article>

# Requesting access at the authorization server # {#h-authz}

In order to access [=protected resources=] at the [=[RS]=], [=clients=] request permission to do so at the [=[AS]=] by sending an [=access request=]: a [:POST:] request to the [=[AS]'s=] [=token endpoint=].

It is [RECOMMENDED] that the body of the [=access request=] is encoded as `application/json`; the [=client=] [MAY] alternatively send it in `application/x-www-form-urlencoded` form, as specified in [[!OAuth20]], [[OAuth20#section-4.1.3|§ 4.1.3]] and exemplified in [[!UMA-Grant]], [[UMA-Grant#uma-grant-type|§ 3.3.1]]. The following common parameters are supported, complemented by the ones listed in [[#h-authz-ticket]] or [[#h-authz-no-ticket]], depending on the use case.

  ISSUE: Go into the combination of `permissions` and `ticket`.

  ISSUE: add support for Rich Authorization Requests and/or JWT-Secured Authorization Requests and/or Pushed Authorization Requests.

<dl noexport dfn-type="dict-member" dfn-for="AccessRequest">

  : <dfn>grant_type</dfn>
  :: [REQUIRED] when presenting a ticket. The type of the [OAuth20] grant presented at the [=token endpoint=]. Within the context of [UMA], the value [MUST] be `urn:ietf:params:oauth:grant-type:uma-ticket`.
  
  : <dfn>claim_token</dfn>
  :: [OPTIONAL]. Directly pushed claim information, provided either on the first or on subsequent requests in the authorization flow. The value is a string, formatted as indicated by the `claim_token_format` parameter. Unless explicitly specified by the indicated format, the string is `base64url` encoded [[!RFC4648]].
  
  : <dfn>claim_token_format</dfn>
  :: [REQUIRED] if the `claim_token` parameter is present. A string specifying the format of the directly pushed claim token. The value [SHOULD] be a [URI], e.g., `http://openid.net/specs/openid-connect-core-1_0.html#IDToken`. 
  
    If `claim_token` parameter is not present, the [=client=] [SHOULD NOT] include the `claim_token_format` parameter either. If it is present in an [=access request=] without a `claim_token` parameter anyway, the [=[AS]=] [MUST] ignore it.

</dl>

  ISSUE: add usage of Persistent Claims Tokens and upgrading of RPTs 

<section>

## Requesting access **with** a permission ticket ## {#h-authz-ticket}

Having received a [=permission ticket=] from the [=[RS]=], the [=client=] can turn to the [=[AS]=] to request access for the [=resources|resource(s)=] and [=scope|scope(s)=] represented by the [=ticket=]. In addition to the common parameters listed above (cf. [[#h-authz]]), such a request [MUST] contain the following parameters.

<dl noexport dfn-type="dict-member" dfn-for="AccessRequest">

  : <dfn>ticket</dfn>
  :: [REQUIRED] when presenting a ticket. The identifier of the [=permission ticket=] that the [=client=] received from the [=[RS]=].

</dl>

For example:

  ```http
  POST /token HTTP/1.1
  Host: as.example.com
  Content-Type: application/json
  ...

  {
    "grant_type": "urn:ietf:params:oauth:grant-type:uma-ticket",
    "ticket": "016f84e8-f9b9-11e0-bd6f-0021cc6004de",
    "claim_token_format": "http://openid.net/specs/openid-connect-core-1_0.html#IDToken",
    "claim_token": "eyj0..."
  }
  ```

</section>
<section>

## Requesting access **without** a permission ticket ## {#h-authz-no-ticket}

For [=clients=] that know the [=resources|resource(s)=] and [=scope|scope(s)=] they want to access, the [A4DS] profile adds a shortcut that saves them the initial request to the [=[RS]=]. Instead, those [=clients=] [MAY] address the [=[AS]=] directly, and include the [=resources|resource(s)=] and [=scope|scope(s)=] directly under the `permissions` parameter. 

<dl noexport dfn-type="dict-member" dfn-for="AccessRequest">

  : <dfn>permissions</dfn>
  :: [REQUIRED] when requesting permissions directly. The [=resources|resource(s)=] and [=scope|scope(s)=] the [=client=] requests access to. The format of this field is identical to that of the [=permission request=] described in [[#h-fed-res-ticket]]: a [=permission description=] object or an array of such objects.

</dl>

  NOTE: Keycloak employs a similar approach, but restricts the value of their `permission` parameter to a single string encoding of [JSON] data. Keycloak also allows such requests to target specific resource URIs, so their AS knows more than a standard UMA server.
 
For example:

  ```http
  POST /token HTTP/1.1
  Host: as.example.com
  Content-Type: application/json
  ...

  {
    "permissions": {
      "resource_id": "KX3A-39WE",
      "resource_scopes": [ 
      "post-updates",
      "http://photoz.example.com/dev/scopes/print"
      ]
    },
    "claim_token_format": "http://openid.net/specs/openid-connect-core-1_0.html#IDToken",
    "claim_token": "eyj0..."
  }
  ```

</section>
<section>

## Requesting extra 'global scopes' ## {#h-authz-extra-scopes}

The [UMA] specification allows the traditional [[OAuth20]] `scope` parameter to be added to an [=access request=], regardless of the [=scopes=] present in the [=ticket=] or in the `permissions` parameter. Each [=scope=] requested in this way applies to all [=resources=] to which the [=access request=] pertains. [=Clients=] can only request such '[=global scopes=]' if they have been pre-registered for those [=scopes=] through a static or dynamic registration client registration mechanism.

<dl noexport dfn-type="dict-member" dfn-for="AccessRequest">

  : <dfn>scope</dfn>
  :: [NOT-RECOMMENDED] A string of space-separated scope identifiers, requesting extra scopes, for which the [=client=] has been pre-registered, that apply to all requested resources.

</dl>

The [A4DS] profile discourages [=access requests=] for such [=global scopes=]. To request resource-specific [=scopes=] that are not included in a [=ticket=] from the [=[RS]=], it is preferable to use the `permissions` parameter specified in [[#h-authz-no-ticket]].

  ISSUE: consider simply disallowing this, and letting 'scope' double as 'permissions', with permission descriptions without a resource id functioning as 'global scopes' (and similar without scope ids functioning as all scopes on one resource). 

</section>

<xmp class="idl">
  dictionary AccessRequest {
    string grant_type;
    string claim_token;
    string claim_token_format;
    string ticket;
    string permissions;
    string scope;
  };
</xmp>

</article>
