
##
# This workflow renders a new version of each changed spec for GitHub Pages.
##

name: GitHub Pages workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch: # for manual runs
    inputs:
      level:
        description: 'Which spec level?'
        default: '1'
        required: true

env:
  build_dir: _gh_pages_build

jobs:

  conditional-build-deploy:
    name: Build and deploy changed specs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Detect changed specs
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.ref }}
          filters: |
            level0: level0/**
            level1: level1/** 
          # level2: level2/**
        id: filter

      - name: Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'
      
      - name: Install Bikeshed
        run: pipx install --python $(which python) --quiet bikeshed
      
      - name: Setup build environment
        run: |
          mkdir -p "${{ env.build_dir }}"/level{0,1,2}
          echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
        id: setup
          
      - name: Build Level 0
        if: ${{ steps.filter.outputs.level0 == 'true' || github.event.inputs.level == '0' }}
        run: |
          cd level0
          bikeshed spec index.bs "../${{ env.build_dir }}"/level0/index.html

      - name: Build Level 1
        if: ${{ steps.filter.outputs.level1 == 'true' || github.event.inputs.level == '1' }}
        run: |
          cd level1
          bikeshed spec index.bs "../${{ env.build_dir }}"/level1/index.html

      # - name: Build Level 2
      #   if: ${{ steps.filter.outputs.level2 == 'true' || github.event.inputs.level == '2' }}
      #   run:  |
      #     cd level2
      #     bikeshed spec index.bs "../${{ env.build_dir }}"/level2/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "${{ env.build_dir }}"
          target-folder: "specs"
          commit-message: "publish: changes at ${{ steps.setup.outputs.timestamp }}"
          branch: gh-pages
          tag: "v${{ steps.setup.outputs.timestamp }}"
          clean: false
