name: Publish spec

on:
  pull_request: {}
  push:
    branches: [ level0 ]

env:
  build_dir: _gh_pages_build

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    strategy:
      matrix:
        spec:
          - in: index.bs
            out: l0
      fail-fast: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'
      - name: Install & run Bikeshed
        id: bikeshed
        run: |
          mkdir -p "${{ env.build_dir }}"
          pipx install --python $(which python) --quiet bikeshed
          bikeshed update
          bikeshed "${{ matrix.spec.in }}" "${{ env.build_dir }}/index.html"
          echo "time=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "${{ env.build_dir }}"
          target-folder: "specs/${{ matrix.spec.out }}"
          commit-message: "publish: level 0 at ${{ steps.bikeshed.outputs.time }}"
          branch: gh-pages
          tag: "l0-${{ steps.bikeshed.outputs.time }}"
          
